import swaggerJsdoc from 'swagger-jsdoc';
import { swaggerPaths } from './swagger-paths.js';

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'API Banco App',
      version: '1.0.0',
      description: 'Documentacao da API Banco App - sistema bancario com usuarios, contas, cartoes, transacoes, PIX, faturas, cobrancas e boletos.',
      contact: {
        name: 'Suporte API',
        email: 'suporte@bancoapp.com',
      },
    },
    servers: [
      {
        url: 'http://localhost:8000',
        description: 'Servidor de desenvolvimento',
      },
      {
        url: 'https://api.bancoapp.com',
        description: 'Servidor de producao',
      },
    ],
    paths: swaggerPaths,
    components: {
      securitySchemes: {
        BearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Token JWT enviado no header Authorization no formato: Bearer {token}',
        },
      },
      schemas: {
        Usuario: {
          type: 'object',
          properties: {
            _id: { type: 'string', example: '6507e8c9a1b234567890abcd' },
            usuario_id: { type: 'integer', example: 1 },
            nome_completo: { type: 'string', example: 'Joao Silva' },
            cpf: { type: 'string', example: '12345678909' },
            data_nascimento: { type: 'string', format: 'date-time', example: '1990-05-15T00:00:00.000Z' },
            email: { type: 'string', format: 'email', example: 'joao@example.com' },
            senha: { type: 'string', description: 'Hash da senha retornado atualmente por algumas rotas de usuario.' },
            telefone: { type: 'string', example: '11999999999' },
            cidade: { type: 'string', example: 'Sao Paulo' },
            estado: { type: 'string', example: 'SP' },
            cep: { type: 'string', example: '01310-100' },
            numero: { type: 'string', example: '123' },
            complemento: { type: 'string', nullable: true, example: 'Apartamento 101' },
            status_conta: { type: 'string', enum: ['ATIVA', 'INATIVA', 'BLOQUEADA', 'EXCLUIDA'], example: 'ATIVA' },
            email_verificado: { type: 'boolean', example: true },
            codigo_verificacao: { type: 'string', nullable: true, example: '123456' },
            codigo_expira: { type: 'string', format: 'date-time', nullable: true },
            email_enviado: { type: 'boolean', example: false },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Conta: {
          type: 'object',
          properties: {
            _id: { type: 'string', example: '6507e8c9a1b234567890abce' },
            id_conta: { type: 'integer', example: 1 },
            usuario_id: { type: 'integer', example: 1 },
            agencia: { type: 'string', example: '0001' },
            numero_conta: { type: 'string', example: '123456' },
            digito: { type: 'string', example: '7' },
            tipo_conta: { type: 'string', enum: ['CORRENTE', 'POUPANCA'], example: 'CORRENTE' },
            saldo: { type: 'number', example: 1500.5 },
            status_conta: { type: 'string', enum: ['ATIVA', 'BLOQUEADA', 'ENCERRADA'], example: 'ATIVA' },
            limite_credito: { type: 'number', example: 200 },
            limite_utilizado: { type: 'number', example: 0 },
            taxa_manutencao: { type: 'number', example: 0 },
            permite_cheque_especial: { type: 'boolean', example: true },
            taxa_rendimento: { type: 'number', example: 0.005 },
            rendimento_acumulado: { type: 'number', example: 0 },
            aniversario_poupanca: { type: 'integer', nullable: true, example: 12 },
            data_abertura: { type: 'string', format: 'date-time' },
            ultima_movimentacao: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Cartao: {
          type: 'object',
          properties: {
            _id: { type: 'string', example: '6507e8c9a1b234567890abcf' },
            id_cartao: { type: 'integer', example: 1 },
            usuario_id: { type: 'integer', example: 1 },
            conta_id: { type: 'number', example: 123456 },
            numero_cartao: { type: 'string', example: '4532123456789012' },
            validade: { type: 'string', example: '05/31' },
            cvv: { type: 'string', example: '123' },
            tipo: { type: 'string', enum: ['DEBITO', 'CREDITO', 'MULTIPLO'], example: 'MULTIPLO' },
            bandeira: { type: 'string', enum: ['VISA', 'MASTERCARD', 'ELO'], example: 'VISA' },
            limite_total: { type: 'number', example: 1000 },
            limite_usado: { type: 'number', example: 250 },
            status_cartao: { type: 'string', enum: ['ATIVO', 'BLOQUEADO', 'CANCELADO'], example: 'ATIVO' },
            data_emissao: { type: 'string', format: 'date-time' },
            data_bloqueio: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Transacao: {
          type: 'object',
          properties: {
            _id: { type: 'string', example: '6507e8c9a1b234567890abd0' },
            id_transacao: { type: 'integer', example: 1 },
            usuario_id: { type: 'integer', example: 1 },
            conta_origem: { type: 'string', example: '123456' },
            conta_destino: { type: 'string', nullable: true, example: '654321' },
            tipo: { type: 'string', enum: ['DEPOSITO', 'SAQUE', 'PIX_ENVIO', 'PIX_RECEBIMENTO'], example: 'PIX_ENVIO' },
            valor: { type: 'number', example: 150 },
            saldo_antes: { type: 'number', example: 1000 },
            saldo_depois: { type: 'number', example: 850 },
            descricao: { type: 'string', nullable: true, example: 'Pagamento aluguel' },
            chave_pix: { type: 'string', nullable: true, example: 'joao@example.com' },
            tipo_chave_pix: { type: 'string', nullable: true, enum: ['CPF', 'EMAIL', 'TELEFONE', 'ALEATORIA', null], example: 'EMAIL' },
            status: { type: 'string', enum: ['CONCLUIDA', 'FALHA'], example: 'CONCLUIDA' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Fatura: {
          type: 'object',
          properties: {
            _id: { type: 'string', example: '6507e8c9a1b234567890abd1' },
            id_fatura: { type: 'integer', example: 1 },
            cartao_id: { type: 'integer', example: 1 },
            conta_id: { type: 'integer', example: 1 },
            mes_referencia: { type: 'string', example: '2026-09' },
            valor_total: { type: 'number', example: 1200.5 },
            data_fechamento: { type: 'string', format: 'date-time' },
            data_vencimento: { type: 'string', format: 'date-time' },
            status_fatura: { type: 'string', enum: ['ABERTA', 'FECHADA', 'PAGA', 'ATRASADA'], example: 'ABERTA' },
            data_pagamento: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ChavePix: {
          type: 'object',
          properties: {
            _id: { type: 'string', example: '6507e8c9a1b234567890abd2' },
            chave: { type: 'string', example: 'joao@example.com' },
            tipo_chave: { type: 'string', enum: ['CPF', 'EMAIL', 'TELEFONE', 'ALEATORIA'], example: 'EMAIL' },
            numero_conta: { type: 'string', example: '123456' },
            usuario_id: { type: 'integer', example: 1 },
            criado_em: { type: 'string', format: 'date-time' },
            __v: { type: 'integer', example: 0 },
          },
        },
        CompraCartao: {
          type: 'object',
          properties: {
            _id: { type: 'string', example: '6507e8c9a1b234567890abd3' },
            id_compra: { type: 'integer', example: 1 },
            usuario_id: { type: 'integer', example: 1 },
            cartao_id: { type: 'string', example: '6507e8c9a1b234567890abcf' },
            valor_total: {
              oneOf: [
                { type: 'number', example: 299.99 },
                { type: 'object', properties: { $numberDecimal: { type: 'string', example: '299.99' } } },
              ],
            },
            valor_parcela: {
              oneOf: [
                { type: 'number', example: 299.99 },
                { type: 'object', properties: { $numberDecimal: { type: 'string', example: '299.99' } } },
              ],
            },
            quantidade_parcelas: { type: 'integer', example: 1 },
            parcela_atual: { type: 'integer', example: 1 },
            descricao: { type: 'string', example: 'Compra no supermercado' },
            data_compra: { type: 'string', format: 'date-time' },
            status_compra: { type: 'string', enum: ['ATIVA', 'CANCELADA', 'ESTORNADA'], example: 'ATIVA' },
            fatura_id: { type: 'string', nullable: true, example: '6507e8c9a1b234567890abd1' },
            incluida_fatura: { type: 'boolean', example: false },
            codigo_autorizacao: { type: 'string', example: 'AUT123456' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Boleto: {
          type: 'object',
          properties: {
            _id: { type: 'string', example: '6507e8c9a1b234567890abd4' },
            usuario_id: { type: 'integer', example: 1 },
            conta_id: { type: 'number', example: 123456 },
            valor: { type: 'number', example: 150 },
            linha_digitavel: { type: 'string', example: '34191.09008 63391.234567 89101.12345 1 00000000012345' },
            codigo_barras: { type: 'string', example: '34191000000000123456339123456789101' },
            vencimento: { type: 'string', format: 'date-time' },
            status: { type: 'string', enum: ['PENDENTE', 'PAGO', 'CANCELADO'], example: 'PENDENTE' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Cobranca: {
          type: 'object',
          properties: {
            _id: { type: 'string', example: '6507e8c9a1b234567890abd5' },
            usuario_id: { type: 'integer', example: 1 },
            valor: { type: 'number', example: 200 },
            codigo_pix: { type: 'string', example: 'PIX-COB-123456' },
            tipo: { type: 'string', example: 'PIX' },
            status: { type: 'string', example: 'PENDENTE' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
            __v: { type: 'integer', example: 0 },
          },
        },
        Error: {
          type: 'object',
          properties: {
            error: { type: 'string', example: 'Erro ao processar requisicao.' },
          },
        },
        FaturaError: {
          type: 'object',
          properties: {
            erro: { type: 'string', example: 'Erro ao processar requisicao.' },
          },
        },
      },
    },
  },
  apis: [],
};

export const specs = swaggerJsdoc(options);
